### ISSUE TITLE
Offset issue :  Use of deprecated `offset` parameter in browse: 

### ISSUE THREAD

**Issue by praveenkumart** [algolia/algoliasearch-client-javascript#1211]
[Inside 'uncaughtException' event] AlgoliaSearchError: Use of deprecated `offset` parameter in browse: you should pass the `cursor` parameter to fetch next page. Please upgrade your api client if necessary
    at success (/var/lib/jenkins/workspace/Gogocar-Algoliasync-PROD/algolia_sync/node_modules/algoliasearch/src/AlgoliaSearchCore.js:377:32)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by Haroenv** [comment]
Hi @praveenkumart, which code were you running when this error was thrown?

**Comment by praveenkumart** [comment]
i'm using version 3.35
it was working till last week

**Comment by Haroenv** [comment]
could you show _which code_ gave this error?

**Comment by shortcuts** [comment]
closing as it should be fixed in v5, feel free to re-open if needed
