### ISSUE TITLE
Cannot get algolia. Json

### ISSUE THREAD

**Issue by tiantian-chen** [algolia/algoliasearch-client-javascript#1262]
I cannot get algolia. Json.Maybe there's something wrong with the process
` hugo-algolia -s
JSON index file was created in public/algolia.json

C:\Users\Administrator\AppData\Roaming\npm\node_modules\hugo-algolia\node_modules\algoliasearch\src\AlgoliaSearchCore.js:50
    throw new errors.AlgoliaSearchError('Please provide an application ID. ' + usage);
    ^
AlgoliaSearchError: Please provide an application ID. Usage: algoliasearch(applicationID, apiKey, opts)
    at AlgoliaSearchNodeJS.AlgoliaSearchCore (C:\Users\Administrator\AppData\Roaming\npm\node_modules\hugo-algolia\node_modules\algoliasearch\src\AlgoliaSearchCore.js:50:11)
    at AlgoliaSearchNodeJS.AlgoliaSearch (C:\Users\Administrator\AppData\Roaming\npm\node_modules\hugo-algolia\node_modules\algoliasearch\src\AlgoliaSearch.js:11:21)
    at AlgoliaSearchNodeJS.AlgoliaSearchServer (C:\Users\Administrator\AppData\Roaming\npm\node_modules\hugo-algolia\node_modules\algoliasearch\src\server\builds\AlgoliaSearchServer.js:17:17)
    at new AlgoliaSearchNodeJS (C:\Users\Administrator\AppData\Roaming\npm\node_modules\hugo-algolia\node_modules\algoliasearch\src\server\builds\node.js:83:23)
    at algoliasearch (C:\Users\Administrator\AppData\Roaming\npm\node_modules\hugo-algolia\node_modules\algoliasearch\src\server\builds\node.js:68:10)
    at HugoAlgolia.HugoAlgolia.sendIndex (C:\Users\Administrator\AppData\Roaming\npm\node_modules\hugo-algolia\lib\index.js:184:20)
    at HugoAlgolia.HugoAlgolia.index (C:\Users\Administrator\AppData\Roaming\npm\node_modules\hugo-algolia\lib\index.js:122:12)
    at Object.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\hugo-algolia\bin\index.js:23:26)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
`

**Comment by Haroenv** [comment]
You probably want to pen this issue in https://github.com/replicatedhq/hugo-algolia instead? This is the repository for the main algolia client, but it's unrelated to how the Hugo plugin instantiates the client
