### ISSUE TITLE
Search client causing app crash on heroku

### ISSUE THREAD

**Issue by xerotolerant** [algolia/algoliasearch-client-javascript#550]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide all the steps to reproduce and a minimal
[JSFiddle](https://jsfiddle.net/) example or a repository on GitHub that we can `npm install`
and `npm start`.**

**What is the expected behavior?**

I am trying to link algolia with firebase following the instructions on the website.
The sample works locally. However when I try to run it on heroku I get the following errors:

```
 /app/dist/algolia/algolia-manager.js:28
2017-05-15T17:40:19.948991+00:00 app[web.1]:                 throw err;
2017-05-15T17:40:19.948991+00:00 app[web.1]:                 ^
2017-05-15T17:40:19.948996+00:00 app[web.1]: AlgoliaSearchNetworkError: getaddrinfo ENOTFOUND bzkq9hqh2-1.algolianet.com bzkq9hqh2-1.algolianet.com:443
2017-05-15T17:40:19.948998+00:00 app[web.1]:     at ClientRequest.error (/app/node_modules/algoliasearch/src/server/builds/node.js:227:14)
2017-05-15T17:40:19.948998+00:00 app[web.1]:     at ClientRequest.g (events.js:292:16)
2017-05-15T17:40:19.948998+00:00 app[web.1]:     at emitOne (events.js:96:13)
2017-05-15T17:40:19.948999+00:00 app[web.1]:     at ClientRequest.emit (events.js:188:7)
2017-05-15T17:40:19.949000+00:00 app[web.1]:     at TLSSocket.socketErrorListener (_http_client.js:309:9)
2017-05-15T17:40:19.949000+00:00 app[web.1]:     at emitOne (events.js:96:13)
2017-05-15T17:40:19.949001+00:00 app[web.1]:     at TLSSocket.emit (events.js:188:7)
2017-05-15T17:40:19.949001+00:00 app[web.1]:     at connectErrorNT (net.js:1021:8)
2017-05-15T17:40:19.949002+00:00 app[web.1]:     at _combinedTickCallback (internal/process/next_tick.js:80:11)
2017-05-15T17:40:19.949002+00:00 app[web.1]:     at process._tickCallback (internal/process/next_tick.js:104:9)
```
it then crashes. I am not sure if anyone else has this problem but I have not been able to find any solution in my searches. What should I do?

**Comment by Haroenv** [comment]
Could you provide us with a reproducible app (as small as possible), that will help a lot with debugging!

**Comment by xerotolerant** [comment]
I just used the sample. https://www.algolia.com/doc/guides/integrations/firebase-algolia/

**Comment by vvo** [comment]
@xerotolerant Can you double check your appid? I think you are missing the last character.

**Comment by xerotolerant** [comment]
Hey that was exactly the problem. Thanks a lot. It probably got messed up when I added it as an environment variable
